#!/bin/bash

cd ${OPENSHIFT_REPO_DIR}

(
  echo [app:main]
  echo sqlalchemy.url = $OPENSHIFT_POSTGRESQL_DB_URL/$PGDATABASE
  echo
  echo [server:main]
  echo host = localhost
  echo port = 8051
  echo
) >> local.ini

pip install -r requirements.txt

python setup.py compile_catalog

cd ${OLDPWD}
